# Properties file with JDBC-related settings applied by PropertyPlaceholderConfigurer.
jdbc.driverClassName=oracle.jdbc.OracleDriver
#jdbc.url=jdbc:oracle:thin:@10.189.41.176:1521:SBIOCAS
jdbc.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=10.189.41.174)(PORT=1580))(CONNECT_DATA=(SERVICE_NAME=SBIOCAS)))
#jdbc.ip=10.189.41.176
jdbc.ip=10.189.41.174
#jdbc.port=1521
jdbc.port=1580
jdbc.name=SBIOCAS
jdbc.username=SBI_TEST
#jdbc.password=sbi_uat#123
jdbc.password=sbi_uat
jdbc.initialSize=25
jdbc.maxActive=200
jdbc.maxIdle=50
jdbc.jmxEnabled=false
jdbc.timeBetweenEvictionRunsMillis=30000
jdbc.removeAbandoned=true
jdbc.removeAbandonedTimeout=30
jdbc.abandonWhenPercentageFull=70
jdbc.testOnBorrow=true
jdbc.validationQuery=SELECT 1 FROM dual
jdbc.validationInterval=30000
jdbc.dialect=org.hibernate.dialect.OracleDialect
#jdbc.dialect=org.hibernate.dialect.Oracle12cDialect
jdbc.show_sql=false
jdbc.database=ORACLE

jdbc.servertype=1
jdbc.name_personal=SBI_PROD

#SMTP Configuration
#sendMail.userName=applyonline@sbi.co.in
sendMail.userName=sbitestclient
#sendMail.password=ocas@123
sendMail.password=sbitestclient_7f827c4b3aa6cd1f08d6b9cce2c0c80e
#sendMail.smtpServerHostName=10.209.32.27
sendMail.smtpServerHostName=10.176.245.236
#sendMail.smtpPort=25
sendMail.smtpPort=587
sendMail.authenticationReqd=true
sendMail.debug=false
#sendMail.fromAddress=applyonline@sbi.co.in
sendMail.fromAddress=itrl_sender@ebmsgits.sbi.co.in
sendMail.staffAddress=applyonline@sbi.co.in
sendMail.alternateAddress=applyonline@sbi.co.in
sendMail.mode=demo

#Deployment Mode Configuration
#settings.deploymentMode=local
settings.deploymentMode=UAT
#settings.deploymentEnvironment=windows
settings.deploymentEnvironment=linux
settings.scriptVersion=1.0.64
settings.scriptCompression=true

##PUT BELOW PROPERTY INSIDE config.properties
#DIP_LOCAL=10.189.41.176
DIP_LOCAL=10.189.41.174
#DPT_LOCAL=1521
DPT_LOCAL=1580
